name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password1234
          MYSQL_DATABASE: uniplus_test
          MYSQL_USER: Hasmitha
          MYSQL_PASSWORD: password1234
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -p$password1234"
          --health-interval=5s --health-timeout=5s --health-retries=10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: 'maven'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          #cache: 'npm'
          #cache-dependency-path: 'frontend/uniplusf/package-lock.json'

      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for MySQL to be ready..."
          for i in {1..30}; do
            mysql -h 127.0.0.1 -P 3306 -u root -ppassword1234 -e "SELECT 1" && break
            echo "waiting..."
            sleep 2
          done

      - name: Create test DB and user
        run: |
          mysql -h 127.0.0.1 -P 3306 -u root -ppassword1234 -e "CREATE DATABASE IF NOT EXISTS uniplus_test CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
          mysql -h 127.0.0.1 -P 3306 -u root -ppassword1234 -e "CREATE USER IF NOT EXISTS 'Hasmitha'@'%' IDENTIFIED BY 'password1234';"
          mysql -h 127.0.0.1 -P 3306 -u root -ppassword1234 -e "GRANT ALL PRIVILEGES ON uniplus_test.* TO 'Hasmitha'@'%';"
          mysql -h 127.0.0.1 -P 3306 -u root -ppassword1234 -e "FLUSH PRIVILEGES;"

      # ---------- Backend (Maven) ----------
      - name: Build & run backend tests (Maven)
        working-directory: ./Backend/uniplus
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/uniplus_test
          SPRING_DATASOURCE_USERNAME: Hasmitha
          SPRING_DATASOURCE_PASSWORD: password1234
        run: |
          java -version
          mvn clean verify -Djunit.jupiter.tags.exclude=ui1,ui2,ui3

      # ---------- Frontend (Vite / Node) ----------
      - name: Install frontend dependencies
        working-directory: ./frontend/uniplusf
        run: |
          npm ci

      - name: Build frontend
        working-directory: ./frontend/uniplusf
        run: |
          npm run build

      # Skip frontend tests since no test script exists in package.json
      - name: Run frontend tests (skipped - no test script)
        working-directory: ./frontend/uniplusf
        run: |
          echo "No test script found in package.json, skipping frontend tests."