name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password1234
          MYSQL_DATABASE: uniplus_test
          MYSQL_USER: Hasmitha
          MYSQL_PASSWORD: password1234
        ports:
          - 3307:3307
        options: >-
          --health-cmd="mysqladmin ping -h localhost -p$password1234"
          --health-interval=5s --health-timeout=5s --health-retries=10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: 'maven'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for MySQL to be ready..."
          for i in {1..30}; do
            mysql -h 127.0.0.1 -P 3307 -u root -ppassword1234 -e "SELECT 1" && break
            echo "waiting..."
            sleep 2
          done

      - name: Create test DB (in case image didn't create)
        run: |
          mysql -h 127.0.0.1 -P 3307 -u root -ppassword1234 -e "CREATE DATABASE IF NOT EXISTS uniplus_test CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci; \
          CREATE USER IF NOT EXISTS 'Hasmitha'@'%' IDENTIFIED BY 'password1234'; \
          GRANT ALL ON uniplus_test.* TO 'Hasmitha'@'%'; FLUSH PRIVILEGES;" || true

      # ---------- Backend (Maven) ----------
      - name: Build & run backend tests (Maven)
        working-directory: ./Backend/uniplus  # <--- update if your backend is at repo root or in a different folder
        run: |
          # show java/mvn versions
          java -version
          mvn -B -V clean verify -DskipTests=false

      # ---------- Frontend (Vite / Node) ----------
      - name: Install frontend dependencies
        working-directory: ./frontend/uniplusf  # <--- update if your frontend is in another folder (or remove this line if frontend is repo root)
        run: |
          npm ci

      - name: Build frontend
        working-directory: ./frontend/uniplusf
        run: |
          npm run build

      - name: Run frontend tests
        working-directory: ./frontend/uniplusf
        run: |
          # Will run `npm test`. Make sure package.json has a test script (see instructions).
          npm test
